#!/bin/sh

[ $# -lt 1 ] && echo "Usage: $(basename $0) %{buildroot}%{ghclibdir} ..." && exit 1

set +x

PKGBASEDIR=${1}
shift
PKGCONFDIR=${PKGBASEDIR}/package.conf.d
GHC_VER=$(basename ${PKGBASEDIR} | sed -e s/ghc-//)

# for a ghc build use the new ghc-pkg
INPLACE_GHCPKG=${PKGBASEDIR}/../../bin/ghc-pkg-${GHC_VER}

if [ -x "${INPLACE_GHCPKG}" ]; then
    GHC_PKG="${PKGBASEDIR}/bin/ghc-pkg --global-package-db=${PKGCONFDIR}"
else
    GHC_PKG="/usr/bin/ghc-pkg-${GHC_VER} -f ${PKGCONFDIR}"
fi

${GHC_PKG} -v0 --simple-output --global $* | uniq
